USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
/*CREATE TABLES IN SCHEMA STAGE_SCH */
CREATE OR REPLACE TABLE CONSUMPTION_SCH.RESTAURANT_LOCATION_DIM (
        RESTAURANT_LOCATION_HK NUMBER PRIMARY KEY,
        -- HASH KEY FOR THE DIMENSION
        LOCATION_ID NUMBER(38, 0) NOT NULL,
        -- BUSINESS KEY
        CITY VARCHAR(100) NOT NULL,
        -- CITY
        STATE VARCHAR(100) NOT NULL,
        -- STATE
        STATE_CODE VARCHAR(2) NOT NULL,
        -- STATE CODE
        IS_UNION_TERRITORY BOOLEAN NOT NULL DEFAULT FALSE,
        -- UNION TERRITORY FLAG
        CAPITAL_CITY_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
        -- CAPITAL CITY FLAG
        CITY_TIER VARCHAR(6),
        -- CITY TIER
        ZIP_CODE VARCHAR(10) NOT NULL,
        -- ZIP CODE
        ACTIVE_FLAG VARCHAR(10) NOT NULL,
        -- ACTIVE FLAG (INDICATING CURRENT RECORD)
        EFF_START_DT TIMESTAMP_TZ(9) NOT NULL,
        -- EFFECTIVE START DATE FOR SCD2
        EFF_END_DT TIMESTAMP_TZ(9),
        -- EFFECTIVE END DATE FOR SCD2
        CURRENT_FLAG BOOLEAN NOT NULL DEFAULT TRUE -- INDICATOR OF THE CURRENT RECORD
    ) COMMENT = 'DIMENSION TABLE FOR RESTAURANT LOCATION WITH SCD2 (SLOWLY CHANGING DIMENSION) ENABLED AND HASHKEY AS SURROGATE KEY';