USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
/*CREATE TABLES IN SCHEMA STAGE_SCH */
CREATE OR REPLACE TABLE STAGE_SCH.LOCATION(
        LOCATIONID TEXT,
        CITY TEXT,
        STATE TEXT,
        ZIPCODE TEXT,
        ACTIVEFLAG TEXT,
        CREATEDDATE TEXT,
        MODIFIEDDATE TEXT,
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
/*CREATE TABLES IN SCHEMA STAGE_SCH */
CREATE OR REPLACE TABLE CLEAN_SCH.RESTAURANT_LOCATION (
        RESTAURANT_LOCATION_SK NUMBER AUTOINCREMENT PRIMARY KEY,
        LOCATION_ID NUMBER NOT NULL UNIQUE,
        CITY STRING(100) NOT NULL,
        STATE STRING(100) NOT NULL,
        STATE_CODE STRING(2) NOT NULL,
        IS_UNION_TERRITORY BOOLEAN NOT NULL DEFAULT FALSE,
        CAPITAL_CITY_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
        CITY_TIER TEXT(6),
        ZIP_CODE STRING(10) NOT NULL,
        ACTIVE_FLAG STRING(10) NOT NULL,
        CREATED_TS TIMESTAMP_TZ NOT NULL,
        MODIFIED_TS TIMESTAMP_TZ,
        -- ADDITIONAL AUDIT COLUMNS
        STG_FILE_NAME STRING,
        STG_FILE_LOAD_TS TIMESTAMP_NTZ,
        STG_FILE_MD5 STRING,
        COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
    );