USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
COPY INTO STAGE_SCH.LOCATION (
    LOCATIONID,
    CITY,
    STATE,
    ZIPCODE,
    ACTIVEFLAG,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS LOCATIONID,
            T.$2::TEXT AS CITY,
            T.$3::TEXT AS STATE,
            T.$4::TEXT AS ZIPCODE,
            T.$5::TEXT AS ACTIVEFLAG,
            T.$6::TEXT AS CREATEDDATE,
            T.$7::TEXT AS MODIFIEDDATE,
            METADATA $FILENAME AS STG_FILE_NAME,
            METADATA $FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA $FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG / INITIAL / LOCATION T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;