USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE STREAM CLEAN_SCH.RESTAURANT_LOCATION_STM ON TABLE CLEAN_SCH.RESTAURANT_LOCATION COMMENT = 'THIS IS THE STANDARD STREAM OBJECT ON RESTAURANT_LOCATION TABLE TO TRACK INSERTS, UPDATES AND DELETES';