USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.MENU AS TARGET USING (
    SELECT TRY_CAST(MENUID AS NUMBER) AS MENU_ID,
        TRY_CAST(RESTAURANTID AS NUMBER) AS RESTAURANT_ID_FK,
        TRY_CAST(ITEMNAME AS STRING) AS ITEM_NAME,
        TRY_CAST(DESCRIPTION AS STRING) AS DESCRIPTION,
        TRY_CAST(PRICE AS NUMBER) AS PRICE,
        TRY_CAST(CATEGORY AS STRING) AS CATEGORY,
        TRY_CAST(AVAILABILITY AS BOOLEAN) AS AVAILABILITY,
        TRY_CAST(ITEMTYPE AS STRING) AS ITEM_TYPE,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.MENU_STM
) AS SOURCE ON TARGET.MENU_ID = SOURCE.MENU_ID
WHEN MATCHED
AND (
    TARGET.RESTAURANT_ID_FK != SOURCE.RESTAURANT_ID_FK
    OR TARGET.ITEM_NAME != SOURCE.ITEM_NAME
    OR TARGET.DESCRIPTION != SOURCE.DESCRIPTION
    OR TARGET.PRICE != SOURCE.PRICE
    OR TARGET.CATEGORY != SOURCE.CATEGORY
    OR TARGET.AVAILABILITY != SOURCE.AVAILABILITY
    OR TARGET.ITEM_TYPE != SOURCE.ITEM_TYPE
) THEN
UPDATE
SET TARGET.RESTAURANT_ID_FK = SOURCE.RESTAURANT_ID_FK,
    TARGET.ITEM_NAME = SOURCE.ITEM_NAME,
    TARGET.DESCRIPTION = SOURCE.DESCRIPTION,
    TARGET.PRICE = SOURCE.PRICE,
    TARGET.CATEGORY = SOURCE.CATEGORY,
    TARGET.AVAILABILITY = SOURCE.AVAILABILITY,
    TARGET.ITEM_TYPE = SOURCE.ITEM_TYPE,
    TARGET.CREATED_DT = SOURCE.CREATED_DT,
    TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        MENU_ID,
        RESTAURANT_ID_FK,
        ITEM_NAME,
        DESCRIPTION,
        PRICE,
        CATEGORY,
        AVAILABILITY,
        ITEM_TYPE,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.MENU_ID,
        SOURCE.RESTAURANT_ID_FK,
        SOURCE.ITEM_NAME,
        SOURCE.DESCRIPTION,
        SOURCE.PRICE,
        SOURCE.CATEGORY,
        SOURCE.AVAILABILITY,
        SOURCE.ITEM_TYPE,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );