USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE SCHEMA CONSUMPTION_SCH;
USE WAREHOUSE COMPUTE_WH;
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_CUSTOMER_DIM FOREIGN KEY (CUSTOMER_DIM_KEY) REFERENCES CONSUMPTION_SCH.CUSTOMER_DIM (CUSTOMER_HK);
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_CUSTOMER_ADDRESS_DIM FOREIGN KEY (CUSTOMER_ADDRESS_DIM_KEY) REFERENCES CONSUMPTION_SCH.CUSTOMER_ADDRESS_DIM (CUSTOMER_ADDRESS_HK);
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_RESTAURANT_DIM FOREIGN KEY (RESTAURANT_DIM_KEY) REFERENCES CONSUMPTION_SCH.RESTAURANT_DIM (RESTAURANT_HK);
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_RESTAURANT_LOCATION_DIM FOREIGN KEY (RESTAURANT_LOCATION_DIM_KEY) REFERENCES CONSUMPTION_SCH.RESTAURANT_LOCATION_DIM (RESTAURANT_LOCATION_HK);
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_MENU_DIM FOREIGN KEY (MENU_DIM_KEY) REFERENCES CONSUMPTION_SCH.MENU_DIM (MENU_DIM_HK);
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_DELIVERY_AGENT_DIM FOREIGN KEY (DELIVERY_AGENT_DIM_KEY) REFERENCES CONSUMPTION_SCH.DELIVERY_AGENT_DIM (DELIVERY_AGENT_HK);
ALTER TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT
ADD CONSTRAINT FK_ORDER_ITEM_FACT_DELIVERY_DATE_DIM FOREIGN KEY (ORDER_DATE_DIM_KEY) REFERENCES CONSUMPTION_SCH.DATE_DIM (DATE_DIM_HK);