-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE SANDBOX;
-- CREATE SCHEMAS --
CREATE SCHEMA IF NOT EXISTS STAGE_SCH;
CREATE SCHEMA IF NOT EXISTS CLEAN_SCH;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION_SCH;
CREATE SCHEMA IF NOT EXISTS COMMON;