USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.RESTAURANT AS TARGET USING (
    SELECT TRY_CAST(RESTAURANTID AS NUMBER) AS RESTAURANT_ID,
        TRY_CAST(NAME AS STRING) AS NAME,
        TRY_CAST(CUISINETYPE AS STRING) AS CUISINE_TYPE,
        TRY_CAST(PRICING_FOR_2 AS NUMBER(10, 2)) AS PRICING_FOR_TWO,
        TRY_CAST(RESTAURANT_PHONE AS STRING) AS RESTAURANT_PHONE,
        TRY_CAST(OPERATINGHOURS AS STRING) AS OPERATING_HOURS,
        TRY_CAST(LOCATIONID AS STRING) AS LOCATION_ID_FK,
        TRY_CAST(ACTIVEFLAG AS STRING) AS ACTIVE_FLAG,
        TRY_CAST(OPENSTATUS AS STRING) AS OPEN_STATUS,
        TRY_CAST(LOCALITY AS STRING) AS LOCALITY,
        TRY_CAST(RESTAURANT_ADDRESS AS STRING) AS RESTAURANT_ADDRESS,
        TRY_CAST(LATITUDE AS NUMBER(9, 6)) AS LATITUDE,
        TRY_CAST(LONGITUDE AS NUMBER(9, 6)) AS LONGITUDE,
        TO_TIMESTAMP_TZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF9') AS CREATED_DT,
        TO_TIMESTAMP_TZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF9') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.RESTAURANT_STM
) AS SOURCE ON TARGET.RESTAURANT_ID = SOURCE.RESTAURANT_ID
WHEN MATCHED
AND (
    TARGET.NAME != SOURCE.NAME
    OR TARGET.CUISINE_TYPE != SOURCE.CUISINE_TYPE
    OR TARGET.PRICING_FOR_TWO != SOURCE.PRICING_FOR_TWO
    OR TARGET.RESTAURANT_PHONE != SOURCE.RESTAURANT_PHONE
    OR TARGET.OPERATING_HOURS != SOURCE.OPERATING_HOURS
    OR TARGET.LOCATION_ID_FK != SOURCE.LOCATION_ID_FK
    OR TARGET.LATITUDE != SOURCE.LATITUDE
    OR TARGET.ACTIVE_FLAG != SOURCE.ACTIVE_FLAG
    OR TARGET.OPEN_STATUS != SOURCE.OPEN_STATUS
    OR TARGET.LOCALITY != SOURCE.LOCALITY
    OR TARGET.RESTAURANT_ADDRESS != SOURCE.RESTAURANT_ADDRESS
    OR TARGET.LATITUDE != SOURCE.LATITUDE
    OR TARGET.LONGITUDE != SOURCE.LONGITUDE
) THEN
UPDATE
SET TARGET.NAME = SOURCE.NAME,
    TARGET.CUISINE_TYPE = SOURCE.CUISINE_TYPE,
    TARGET.PRICING_FOR_TWO = SOURCE.PRICING_FOR_TWO,
    TARGET.RESTAURANT_PHONE = SOURCE.RESTAURANT_PHONE,
    TARGET.OPERATING_HOURS = SOURCE.OPERATING_HOURS,
    TARGET.LOCATION_ID_FK = SOURCE.LOCATION_ID_FK,
    TARGET.ACTIVE_FLAG = SOURCE.ACTIVE_FLAG,
    TARGET.OPEN_STATUS = SOURCE.OPEN_STATUS,
    TARGET.LOCALITY = SOURCE.LOCALITY,
    TARGET.RESTAURANT_ADDRESS = SOURCE.RESTAURANT_ADDRESS,
    TARGET.LATITUDE = SOURCE.LATITUDE,
    TARGET.LONGITUDE = SOURCE.LONGITUDE,
    TARGET.CREATED_DT = SOURCE.CREATED_DT,
    TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        RESTAURANT_ID,
        NAME,
        CUISINE_TYPE,
        PRICING_FOR_TWO,
        RESTAURANT_PHONE,
        OPERATING_HOURS,
        LOCATION_ID_FK,
        ACTIVE_FLAG,
        OPEN_STATUS,
        LOCALITY,
        RESTAURANT_ADDRESS,
        LATITUDE,
        LONGITUDE,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.RESTAURANT_ID,
        SOURCE.NAME,
        SOURCE.CUISINE_TYPE,
        SOURCE.PRICING_FOR_TWO,
        SOURCE.RESTAURANT_PHONE,
        SOURCE.OPERATING_HOURS,
        SOURCE.LOCATION_ID_FK,
        SOURCE.ACTIVE_FLAG,
        SOURCE.OPEN_STATUS,
        SOURCE.LOCALITY,
        SOURCE.RESTAURANT_ADDRESS,
        SOURCE.LATITUDE,
        SOURCE.LONGITUDE,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );