USE ROLE SYSADMIN;

USE DATABASE SANDBOX;

USE WAREHOUSE COMPUTE_WH;

MERGE INTO
    CLEAN_SCH.ORDERS AS TARGET USING (
        SELECT
            TRY_CAST(ORDERID AS NUMBER) AS ORDER_ID,
            TRY_CAST(CUSTOMERID AS NUMBER) AS CUSTOMER_ID_FK,
            TRY_CAST(RESTAURANTID AS NUMBER) AS RESTAURANT_ID_FK,
            TRY_TO_TIMESTAMP_NTZ(ORDERDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS ORDER_DATE,
            TRY_CAST(TOTALAMOUNT AS NUMBER(38,3)) AS TOTAL_AMOUNT,
            TRY_CAST(STATUS AS STRING) AS STATUS,
            TRY_CAST(PAYMENTMETHOD AS STRING) AS PAYMENT_METHOD,
            TRY_TO_TIMESTAMP_NTZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS CREATED_DT,
            TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS MODIFIED_DT,
            STG_FILE_NAME,
            STG_FILE_LOAD_TS,
            STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM
            STAGE_SCH.ORDERS_STM
    ) AS SOURCE ON TARGET.ORDER_ID = SOURCE.ORDER_ID
WHEN MATCHED AND
    (

        TARGET.CUSTOMER_ID_FK != SOURCE.CUSTOMER_ID_FK OR 
        TARGET.RESTAURANT_ID_FK != SOURCE.RESTAURANT_ID_FK OR
        TARGET.ORDER_DATE != SOURCE.ORDER_DATE OR
        TARGET.TOTAL_AMOUNT != SOURCE.TOTAL_AMOUNT OR
        TARGET.STATUS != SOURCE.STATUS OR
        TARGET.PAYMENT_METHOD != SOURCE.PAYMENT_METHOD 

    )

THEN UPDATE SET

        TARGET.CUSTOMER_ID_FK = SOURCE.CUSTOMER_ID_FK,
        TARGET.RESTAURANT_ID_FK = SOURCE.RESTAURANT_ID_FK,
        TARGET.ORDER_DATE = SOURCE.ORDER_DATE,
        TARGET.TOTAL_AMOUNT = SOURCE.TOTAL_AMOUNT,
        TARGET.STATUS = SOURCE.STATUS,
        TARGET.PAYMENT_METHOD = SOURCE.PAYMENT_METHOD,
        
        --UPDATING AUDIT COLUMS--

        TARGET.CREATED_DT = SOURCE.CREATED_DT,
        TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
        TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
        TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
        TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
        TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS

WHEN NOT MATCHED THEN INSERT
    (
      ORDER_ID, 
      CUSTOMER_ID_FK, 
      RESTAURANT_ID_FK, 
      ORDER_DATE, 
      TOTAL_AMOUNT, 
      STATUS, 
      PAYMENT_METHOD, 
      CREATED_DT, 
      MODIFIED_DT, 
      STG_FILE_NAME, 
      STG_FILE_LOAD_TS, 
      STG_FILE_MD5, 
      COPY_DATA_TS
    )
VALUES
    (
      SOURCE.ORDER_ID, 
      SOURCE.CUSTOMER_ID_FK, 
      SOURCE.RESTAURANT_ID_FK, 
      SOURCE.ORDER_DATE, 
      SOURCE.TOTAL_AMOUNT, 
      SOURCE.STATUS, 
      SOURCE.PAYMENT_METHOD, 
      SOURCE.CREATED_DT, 
      SOURCE.MODIFIED_DT, 
      SOURCE.STG_FILE_NAME, 
      SOURCE.STG_FILE_LOAD_TS, 
      SOURCE.STG_FILE_MD5, 
      SOURCE.COPY_DATA_TS
    );
