USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.DELIVERY AS TARGET USING (
    SELECT TRY_CAST(DELIVERYID AS NUMBER) AS DELIVERY_ID,
        TRY_CAST(ORDERID AS NUMBER) AS ORDER_ID_FK,
        TRY_CAST(DELIVERYAGENTID AS STRING) AS DELIVERY_AGENT_ID_FK,
        TRY_CAST(DELIVERYSTATUS AS STRING) AS DELIVERY_STATUS,
        TRY_CAST(ESTIMATEDTIME AS STRING) AS ESTIMATED_TIME,
        TRY_CAST(ADDRESSID AS STRING) AS CUSTOMER_ADDRESS_ID_FK,
        TRY_TO_TIMESTAMP_NTZ(DELIVERYDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS DELIVERY_DATE,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.DELIVERY_STM
) AS SOURCE ON TARGET.DELIVERY_ID = SOURCE.DELIVERY_ID
WHEN MATCHED
AND (
    TARGET.ORDER_ID_FK != SOURCE.ORDER_ID_FK
    OR TARGET.DELIVERY_AGENT_ID_FK != SOURCE.DELIVERY_AGENT_ID_FK
    OR TARGET.DELIVERY_STATUS != SOURCE.DELIVERY_STATUS
    OR TARGET.ESTIMATED_TIME != SOURCE.ESTIMATED_TIME
    OR TARGET.CUSTOMER_ADDRESS_ID_FK != SOURCE.CUSTOMER_ADDRESS_ID_FK
    OR TARGET.DELIVERY_DATE != SOURCE.DELIVERY_DATE
) THEN
UPDATE
SET TARGET.ORDER_ID_FK = SOURCE.ORDER_ID_FK,
    TARGET.DELIVERY_AGENT_ID_FK = SOURCE.DELIVERY_AGENT_ID_FK,
    TARGET.DELIVERY_STATUS = SOURCE.DELIVERY_STATUS,
    TARGET.ESTIMATED_TIME = SOURCE.ESTIMATED_TIME,
    TARGET.CUSTOMER_ADDRESS_ID_FK = SOURCE.CUSTOMER_ADDRESS_ID_FK,
    TARGET.DELIVERY_DATE = SOURCE.DELIVERY_DATE,
    --UPDATING AUDIT COLUMS--
    TARGET.CREATED_DT = SOURCE.CREATED_DT,
    TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        DELIVERY_ID,
        ORDER_ID_FK,
        DELIVERY_AGENT_ID_FK,
        DELIVERY_STATUS,
        ESTIMATED_TIME,
        CUSTOMER_ADDRESS_ID_FK,
        DELIVERY_DATE,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.DELIVERY_ID,
        SOURCE.ORDER_ID_FK,
        SOURCE.DELIVERY_AGENT_ID_FK,
        SOURCE.DELIVERY_STATUS,
        SOURCE.ESTIMATED_TIME,
        SOURCE.CUSTOMER_ADDRESS_ID_FK,
        SOURCE.DELIVERY_DATE,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );