-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE VIRTUAL WAREHOUSE--
USE WAREHOUSE COMPUTE_WH;
-- USE DATABASE --
USE DATABASE SANDBOX;
-- CREATE SCHEMAS --
USE SCHEMA STAGE_SCH;
-- CREATE FILE FORMAT --
CREATE FILE FORMAT IF NOT EXISTS STAGE_SCH.CSV_FILE_FORMAT TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\N' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('\\N');
-- CREATE STAGE --
CREATE STAGE IF NOT EXISTS STAGE_SCH.CSV_STG DIRECTORY = (ENABLE = TRUE) COMMENT = 'THIS IS A SNOWFLAKE INTERNAL STAGE';