USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CONSUMPTION_SCH.RESTAURANT_LOCATION_DIM AS TARGET USING CLEAN_SCH.RESTAURANT_LOCATION_STM AS SOURCE ON TARGET.LOCATION_ID = SOURCE.LOCATION_ID
AND TARGET.ACTIVE_FLAG = SOURCE.ACTIVE_FLAG
WHEN MATCHED
AND SOURCE.METADATA$ACTION = 'DELETE'
AND SOURCE.METADATA$ISUPDATE = TRUE THEN
UPDATE
SET TARGET.EFF_END_DT = CURRENT_TIMESTAMP(),
    TARGET.CURRENT_FLAG = FALSE
    WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT'
    AND SOURCE.METADATA$ISUPDATE = TRUE THEN
INSERT (
        RESTAURANT_LOCATION_HK,
        LOCATION_ID,
        CITY,
        STATE,
        STATE_CODE,
        IS_UNION_TERRITORY,
        CAPITAL_CITY_FLAG,
        CITY_TIER,
        ZIP_CODE,
        ACTIVE_FLAG,
        EFF_START_DT,
        EFF_END_DT,
        CURRENT_FLAG
    )
VALUES (
        HASH(
            SHA1_HEX(
                CONCAT(
                    SOURCE.CITY,
                    SOURCE.STATE,
                    SOURCE.STATE_CODE,
                    SOURCE.ZIP_CODE
                )
            )
        ),
        SOURCE.LOCATION_ID,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.STATE_CODE,
        SOURCE.IS_UNION_TERRITORY,
        SOURCE.CAPITAL_CITY_FLAG,
        SOURCE.CITY_TIER,
        SOURCE.ZIP_CODE,
        SOURCE.ACTIVE_FLAG,
        CURRENT_TIMESTAMP(),
        NULL,
        TRUE
    )
    WHEN NOT MATCHED THEN
INSERT (
        RESTAURANT_LOCATION_HK,
        LOCATION_ID,
        CITY,
        STATE,
        STATE_CODE,
        IS_UNION_TERRITORY,
        CAPITAL_CITY_FLAG,
        CITY_TIER,
        ZIP_CODE,
        ACTIVE_FLAG,
        EFF_START_DT,
        EFF_END_DT,
        CURRENT_FLAG
    )
VALUES (
        HASH(
            SHA1_HEX(
                CONCAT(
                    SOURCE.CITY,
                    SOURCE.STATE,
                    SOURCE.STATE_CODE,
                    SOURCE.ZIP_CODE
                )
            )
        ),
        SOURCE.LOCATION_ID,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.STATE_CODE,
        SOURCE.IS_UNION_TERRITORY,
        SOURCE.CAPITAL_CITY_FLAG,
        SOURCE.CITY_TIER,
        SOURCE.ZIP_CODE,
        SOURCE.ACTIVE_FLAG,
        CURRENT_TIMESTAMP(),
        NULL,
        TRUE
    );