USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.CUSTOMER AS TARGET USING (
    SELECT TRY_CAST(CUSTOMERID AS NUMBER) AS CUSTOMER_ID,
        TRY_CAST(NAME AS STRING) AS NAME,
        TRY_CAST(MOBILE AS STRING) AS MOBILE,
        TRY_CAST(EMAIL AS STRING) AS EMAIL,
        TRY_CAST(LOGINBYUSING AS STRING) AS LOGIN_BY_USING,
        TRY_CAST(GENDER AS STRING) AS GENDER,
        TRY_TO_DATE(DOB, 'YYYY-MM-DD') AS DOB,
        TRY_TO_DATE(ANNIVERSARY, 'YYYY-MM-DD') AS ANNIVERSARY,
        TRY_CAST(PREFERENCES AS STRING) AS PREFERENCES,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE, 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS CREATED_DT,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE, 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.CUSTOMER_STM
) AS SOURCE ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
WHEN MATCHED
AND (
    TARGET.NAME != SOURCE.NAME
    OR TARGET.MOBILE != SOURCE.MOBILE
    OR TARGET.EMAIL != SOURCE.EMAIL
    OR TARGET.LOGIN_BY_USING != SOURCE.LOGIN_BY_USING
    OR TARGET.GENDER != SOURCE.GENDER
    OR TARGET.DOB != SOURCE.DOB
    OR TARGET.ANNIVERSARY != SOURCE.ANNIVERSARY
    OR TARGET.PREFERENCES != SOURCE.PREFERENCES
) THEN
UPDATE
SET TARGET.NAME = SOURCE.NAME,
    TARGET.MOBILE = SOURCE.MOBILE,
    TARGET.EMAIL = SOURCE.EMAIL,
    TARGET.LOGIN_BY_USING = SOURCE.LOGIN_BY_USING,
    TARGET.GENDER = SOURCE.GENDER,
    TARGET.DOB = SOURCE.DOB,
    TARGET.ANNIVERSARY = SOURCE.ANNIVERSARY,
    TARGET.PREFERENCES = SOURCE.PREFERENCES,
    TARGET.CREATED_DT = SOURCE.CREATED_DT,
    TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        CUSTOMER_ID,
        NAME,
        EMAIL,
        LOGIN_BY_USING,
        GENDER,
        DOB,
        ANNIVERSARY,
        PREFERENCES,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.CUSTOMER_ID,
        SOURCE.NAME,
        SOURCE.EMAIL,
        SOURCE.LOGIN_BY_USING,
        SOURCE.GENDER,
        SOURCE.DOB,
        SOURCE.ANNIVERSARY,
        SOURCE.PREFERENCES,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );