USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE DATA_LOAD_WH;
/*COPY DATA FROM NAMED INTERNAL STAGE  TO STAGING TABLE */
COPY INTO STAGE_SCH.LOCATION (
    LOCATIONID,
    CITY,
    STATE,
    ZIPCODE,
    ACTIVEFLAG,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS LOCATIONID,
            T.$2::TEXT AS CITY,
            T.$3::TEXT AS STATE,
            T.$4::TEXT AS ZIPCODE,
            T.$5::TEXT AS ACTIVEFLAG,
            T.$6::TEXT AS CREATEDDATE,
            T.$7::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/location T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.RESTAURANT (
    RESTAURANTID,
    NAME,
    CUISINETYPE,
    PRICING_FOR_2,
    RESTAURANT_PHONE,
    OPERATINGHOURS,
    LOCATIONID,
    ACTIVEFLAG,
    OPENSTATUS,
    LOCALITY,
    RESTAURANT_ADDRESS,
    LATITUDE,
    LONGITUDE,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS RESTAURANTID,
            T.$2::TEXT AS NAME,
            T.$3::TEXT AS CUISINETYPE,
            T.$4::TEXT AS PRICING_FOR_2,
            T.$5::TEXT AS RESTAURANT_PHONE,
            T.$6::TEXT AS OPERATINGHOURS,
            T.$7::TEXT AS LOCATIONID,
            T.$8::TEXT AS ACTIVEFLAG,
            T.$9::TEXT AS OPENSTATUS,
            T.$10::TEXT AS LOCALITY,
            T.$11::TEXT AS RESTAURANT_ADDRESS,
            T.$12::TEXT AS LATITUDE,
            T.$13::TEXT AS LONGITUDE,
            T.$14::TEXT AS CREATEDDATE,
            T.$15::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/restaurant T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.CUSTOMER (
    CUSTOMERID,
    NAME,
    MOBILE,
    EMAIL,
    LOGINBYUSING,
    GENDER,
    DOB,
    ANNIVERSARY,
    PREFERENCES,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS CUSTOMERID,
            T.$2::TEXT AS NAME,
            T.$3::TEXT AS MOBILE,
            T.$4::TEXT AS EMAIL,
            T.$5::TEXT AS LOGINBYUSING,
            T.$6::TEXT AS GENDER,
            T.$7::TEXT AS DOB,
            T.$8::TEXT AS ANNIVERSARY,
            T.$9::TEXT AS PREFERENCES,
            T.$10::TEXT AS CREATEDDATE,
            T.$11::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/customers T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.CUSTOMERADDRESS (
    ADDRESSID,
    CUSTOMERID,
    FLATNO,
    HOUSENO,
    FLOOR,
    BUILDING,
    LANDMARK,
    LOCALITY,
    CITY,
    PINCODE,
    STATE,
    COORDINATES,
    PRIMARYFLAG,
    ADDRESSTYPE,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS ADDRESSID,
            T.$2::TEXT AS CUSTOMERID,
            T.$3::TEXT AS FLATNO,
            T.$4::TEXT AS HOUSENO,
            T.$5::TEXT AS FLOOR,
            T.$6::TEXT AS BUILDING,
            T.$7::TEXT AS LANDMARK,
            T.$8::TEXT AS LOCALITY,
            T.$9::TEXT AS CITY,
            T.$10::TEXT AS STATE,
            T.$11::TEXT AS PINCODE,
            T.$12::TEXT AS COORDINATES,
            T.$13::TEXT AS PRIMARYFLAG,
            T.$14::TEXT AS ADDRESSTYPE,
            T.$15::TEXT AS CREATEDDATE,
            T.$16::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/customer_address T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.MENU (
    MENUID,
    RESTAURANTID,
    ITEMNAME,
    DESCRIPTION,
    PRICE,
    CATEGORY,
    AVAILABILITY,
    ITEMTYPE,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS MENUID,
            T.$2::TEXT AS RESTAURANTID,
            T.$3::TEXT AS ITEMNAME,
            T.$4::TEXT AS DESCRIPTION,
            T.$5::TEXT AS PRICE,
            T.$6::TEXT AS CATEGORY,
            T.$7::TEXT AS AVAILABILITY,
            T.$8::TEXT AS ITEMTYPE,
            T.$9::TEXT AS CREATEDDATE,
            T.$10::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/menu T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.DELIVERYAGENT (
    DELIVERYAGENTID,
    NAME,
    PHONE,
    VEHICLETYPE,
    LOCATIONID,
    STATUS,
    GENDER,
    RATING,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS DELIVERYAGENTID,
            T.$2::TEXT AS NAME,
            T.$3::TEXT AS PHONE,
            T.$4::TEXT AS VEHICLETYPE,
            T.$5::TEXT AS LOCATIONID,
            T.$6::TEXT AS STATUS,
            T.$7::TEXT AS GENDER,
            T.$8::TEXT AS RATING,
            T.$9::TEXT AS CREATEDDATE,
            T.$10::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/delivery_agent T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.DELIVERY (
    DELIVERYID,
    ORDERID,
    DELIVERYAGENTID,
    DELIVERYSTATUS,
    ESTIMATEDTIME,
    ADDRESSID,
    DELIVERYDATE,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS DELIVERYID,
            T.$2::TEXT AS ORDERID,
            T.$3::TEXT AS DELIVERYAGENTID,
            T.$4::TEXT AS DELIVERYSTATUS,
            T.$5::TEXT AS ESTIMATEDTIME,
            T.$6::TEXT AS ADDRESSID,
            T.$7::TEXT AS DELIVERYDATE,
            T.$8::TEXT AS CREATEDDATE,
            T.$9::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/delivery T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.ORDERS (
    ORDERID,
    CUSTOMERID,
    RESTAURANTID,
    ORDERDATE,
    TOTALAMOUNT,
    STATUS,
    PAYMENTMETHOD,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS ORDERID,
            T.$2::TEXT AS CUSTOMERID,
            T.$3::TEXT AS RESTAURANTID,
            T.$4::TEXT AS ORDERDATE,
            T.$5::TEXT AS TOTALAMOUNT,
            T.$6::TEXT AS STATUS,
            T.$7::TEXT AS PAYMENTMETHOD,
            T.$8::TEXT AS CREATEDDATE,
            T.$9::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/order T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;
COPY INTO STAGE_SCH.ORDERITEM (
    ORDERITEMID,
    ORDERID,
    MENUID,
    QUANTITY,
    PRICE,
    SUBTOTAL,
    CREATEDDATE,
    MODIFIEDDATE,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5,
    COPY_DATA_TS
)
FROM (
        SELECT T.$1::TEXT AS ORDERITEMID,
            T.$2::TEXT AS ORDERID,
            T.$3::TEXT AS MENUID,
            T.$4::TEXT AS QUANTITY,
            T.$5::TEXT AS PRICE,
            T.$6::TEXT AS SUBTOTAL,
            T.$7::TEXT AS CREATEDDATE,
            T.$8::TEXT AS MODIFIEDDATE,
            METADATA$FILENAME AS STG_FILE_NAME,
            METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
            METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
            CURRENT_TIMESTAMP AS COPY_DATA_TS
        FROM @STAGE_SCH.CSV_STG/initial/order_item T
    ) FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT') ON_ERROR = ABORT_STATEMENT;