USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE SCHEMA CLEAN_SCH;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE STREAM CLEAN_SCH.RESTAURANT_LOCATION_STM ON TABLE CLEAN_SCH.RESTAURANT_LOCATION COMMENT = 'THIS IS THE STANDARD STREAM OBJECT ON RESTAURANT_LOCATION TABLE TO TRACK INSERTS, UPDATES AND DELETES';
CREATE OR REPLACE STREAM CLEAN_SCH.RESTAURANT_STM ON TABLE CLEAN_SCH.RESTAURANT COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN RESTAURANT TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.CUSTOMER_STM ON TABLE CLEAN_SCH.CUSTOMER COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN CUSTOMER TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.CUSTOMERADDRESS_STM ON TABLE CLEAN_SCH.CUSTOMER_ADDRESS COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN CUSTOMERADDRESS TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.MENU_STM ON TABLE CLEAN_SCH.MENU COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN MENU TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.DELIVERYAGENT_STM ON TABLE CLEAN_SCH.DELIVERY_AGENT COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN DELIVERYAGENT TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.DELIVERY_STM ON TABLE CLEAN_SCH.DELIVERY COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN DELIVERY TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.ORDERS_STM ON TABLE CLEAN_SCH.ORDERS COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN ORDERS TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';
CREATE OR REPLACE STREAM CLEAN_SCH.ORDERITEM_STM ON TABLE CLEAN_SCH.ORDER_ITEM COMMENT = 'THIS IS A STANDARD STREAM OBJECT ON THE CLEAN ORDERITEM TABLE TO TRACK INSERT, UPDATE, AND DELETE CHANGES';