USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE TAG COMMON.PII_POLICY_TAG ALLOWED_VALUES 'PII',
    'PRICE',
    'SENSITIVE',
    'EMAIL' COMMENT = 'THIS IS PII POLICY TAG OBJECT';
CREATE OR REPLACE MASKING POLICY COMMON.PII_MASKING_POLICY AS (PII_TEXT STRING) RETURNS STRING->TO_VARCHAR('** PII **');
CREATE OR REPLACE MASKING POLICY COMMON.EMAIL_MASKING_POLICY AS (EMAIL_TEXT STRING) RETURNS STRING->TO_VARCHAR('** EAMIL **');
CREATE OR REPLACE MASKING POLICY COMMON.PHONE_MASKING_POLICY AS (PHONE STRING) RETURNS STRING->TO_VARCHAR('** PHONE **');