USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE SCHEMA STAGE_SCH;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE TABLE STAGE_SCH.LOCATION(
        LOCATIONID TEXT,
        CITY TEXT,
        STATE TEXT,
        ZIPCODE TEXT,
        ACTIVEFLAG TEXT,
        CREATEDDATE TEXT,
        MODIFIEDDATE TEXT,
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
-- CREATE RESTAURANT TABLE UNDER STAGE LOCATION, WITH ALL TEXT VALUE + AUDIT COLUMN FOR COPY COMMAND
CREATE OR REPLACE TABLE STAGE_SCH.RESTAURANT (
        RESTAURANTID TEXT,
        NAME TEXT,
        -- RESTAURANT NAME, REQUIRED FIELD
        CUISINETYPE TEXT,
        -- TYPE OF CUISINE OFFERED
        PRICING_FOR_2 TEXT,
        -- PRICING FOR TWO PEOPLE AS TEXT
        RESTAURANT_PHONE TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
        -- PHONE NUMBER AS TEXT
        OPERATINGHOURS TEXT,
        -- RESTAURANT OPERATING HOURS
        LOCATIONID TEXT,
        -- LOCATION ID, DEFAULT AS TEXT
        ACTIVEFLAG TEXT,
        -- ACTIVE STATUS
        OPENSTATUS TEXT,
        -- OPEN STATUS
        LOCALITY TEXT,
        -- LOCALITY AS TEXT
        RESTAURANT_ADDRESS TEXT,
        -- ADDRESS AS TEXT
        LATITUDE TEXT,
        -- LATITUDE AS TEXT FOR PRECISION
        LONGITUDE TEXT,
        -- LONGITUDE AS TEXT FOR PRECISION
        CREATEDDATE TEXT,
        -- RECORD CREATION DATE
        MODIFIEDDATE TEXT,
        -- LAST MODIFIED DATE
        -- AUDIT COLUMNS FOR DEBUGGING
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) COMMENT = 'THIS IS THE RESTAURANT STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
-- CREATE RESTAURANT TABLE UNDER STAGE, WITH ALL TEXT VALUE + AUDIT COLUMN FOR COPY COMMAND
CREATE OR REPLACE TABLE STAGE_SCH.CUSTOMER (
        CUSTOMERID TEXT,
        -- PRIMARY KEY AS TEXT
        NAME TEXT,
        -- NAME AS TEXT
        MOBILE TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
        -- MOBILE NUMBER AS TEXT
        EMAIL TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),
        -- EMAIL AS TEXT
        LOGINBYUSING TEXT,
        -- LOGIN METHOD AS TEXT
        GENDER TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
        -- GENDER AS TEXT
        DOB TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
        -- DATE OF BIRTH AS TEXT
        ANNIVERSARY TEXT,
        -- ANNIVERSARY AS TEXT
        PREFERENCES TEXT,
        -- PREFERENCES AS TEXT
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) COMMENT = 'THIS IS THE CUSTOMER STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
CREATE OR REPLACE TABLE STAGE_SCH.CUSTOMERADDRESS (
        ADDRESSID TEXT,
        -- PRIMARY KEY AS TEXT
        CUSTOMERID TEXT COMMENT 'CUSTOMER FK (SOURCE DATA)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        FLATNO TEXT,
        -- FLAT NUMBER AS TEXT
        HOUSENO TEXT,
        -- HOUSE NUMBER AS TEXT
        FLOOR TEXT,
        -- FLOOR AS TEXT
        BUILDING TEXT,
        -- BUILDING NAME AS TEXT
        LANDMARK TEXT,
        -- LANDMARK AS TEXT
        LOCALITY TEXT,
        -- LOCALITY AS TEXT
        CITY TEXT,
        -- CITY AS TEXT
        STATE TEXT,
        -- STATE AS TEXT
        PINCODE TEXT,
        -- PINCODE AS TEXT
        COORDINATES TEXT,
        -- COORDINATES AS TEXT
        PRIMARYFLAG TEXT,
        -- PRIMARY FLAG AS TEXT
        ADDRESSTYPE TEXT,
        -- ADDRESS TYPE AS TEXT
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) COMMENT = 'THIS IS THE CUSTOMER ADDRESS STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
CREATE OR REPLACE TABLE STAGE_SCH.MENU (
        MENUID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- PRIMARY KEY AS TEXT
        RESTAURANTID TEXT COMMENT 'RESTAURANT FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        ITEMNAME TEXT,
        -- ITEM NAME AS TEXT
        DESCRIPTION TEXT,
        -- DESCRIPTION AS TEXT
        PRICE TEXT,
        -- PRICE AS TEXT (NO DECIMAL CONSTRAINT)
        CATEGORY TEXT,
        -- CATEGORY AS TEXT
        AVAILABILITY TEXT,
        -- AVAILABILITY AS TEXT
        ITEMTYPE TEXT,
        -- ITEM TYPE AS TEXT
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) COMMENT = 'THIS IS THE MENU STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
CREATE OR REPLACE TABLE STAGE_SCH.DELIVERYAGENT (
        DELIVERYAGENTID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- PRIMARY KEY AS TEXT
        NAME TEXT,
        -- NAME AS TEXT, REQUIRED FIELD
        PHONE TEXT,
        -- PHONE AS TEXT, UNIQUE CONSTRAINT INDICATED
        VEHICLETYPE TEXT,
        -- VEHICLE TYPE AS TEXT
        LOCATIONID TEXT,
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        STATUS TEXT,
        -- STATUS AS TEXT
        GENDER TEXT,
        -- STATUS AS TEXT
        RATING TEXT,
        -- RATING AS TEXT
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE OR REPLACE TABLE STAGE_SCH.DELIVERY (
        DELIVERYID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        ORDERID TEXT COMMENT 'ORDER FK (SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        DELIVERYAGENTID TEXT COMMENT 'DELIVERY AGENT FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        DELIVERYSTATUS TEXT,
        -- DELIVERY STATUS AS TEXT
        ESTIMATEDTIME TEXT,
        -- ESTIMATED TIME AS TEXT
        ADDRESSID TEXT COMMENT 'CUSTOMER ADDRESS FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        DELIVERYDATE TEXT,
        -- DELIVERY DATE AS TEXT
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE OR REPLACE TABLE STAGE_SCH.ORDERS (
        ORDERID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- PRIMARY KEY AS TEXT
        CUSTOMERID TEXT COMMENT 'CUSTOMER FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        RESTAURANTID TEXT COMMENT 'RESTAURANT FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        ORDERDATE TEXT,
        -- ORDER DATE AS TEXT
        TOTALAMOUNT TEXT,
        -- TOTAL AMOUNT AS TEXT (NO DECIMAL CONSTRAINT)
        STATUS TEXT,
        -- STATUS AS TEXT
        PAYMENTMETHOD TEXT,
        -- PAYMENT METHOD AS TEXT
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE OR REPLACE TABLE STAGE_SCH.ORDERITEM (
        ORDERITEMID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- PRIMARY KEY AS TEXT
        ORDERID TEXT COMMENT 'ORDER FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        MENUID TEXT COMMENT 'MENU FK(SOURCE SYSTEM)',
        -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
        QUANTITY TEXT,
        -- QUANTITY AS TEXT
        PRICE TEXT,
        -- PRICE AS TEXT (NO DECIMAL CONSTRAINT)
        SUBTOTAL TEXT,
        -- SUBTOTAL AS TEXT (NO DECIMAL CONSTRAINT)
        CREATEDDATE TEXT,
        -- CREATED DATE AS TEXT
        MODIFIEDDATE TEXT,
        -- MODIFIED DATE AS TEXT
        -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
        STG_FILE_NAME TEXT,
        STG_FILE_LOAD_TS TIMESTAMP,
        STG_FILE_MD5 TEXT,
        COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );