USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.CUSTOMER_ADDRESS AS TARGET USING (
    SELECT TRY_CAST(ADDRESSID AS NUMBER) AS ADDRESS_ID,
        TRY_CAST(CUSTOMERID AS NUMBER) AS CUSTOMER_ID_FK,
        TRY_CAST(FLATNO AS STRING) AS FLAT_NO,
        TRY_CAST(HOUSENO AS STRING) AS HOUSE_NO,
        TRY_CAST(FLOOR AS STRING) AS FLOOR,
        TRY_CAST(BUILDING AS STRING) AS BUILDING,
        TRY_CAST(LANDMARK AS STRING) AS LANDMARK,
        TRY_CAST(LOCALITY AS STRING) AS LOCALITY,
        TRY_CAST(CITY AS STRING) AS CITY,
        TRY_CAST(STATE AS STRING) AS STATE,
        TRY_CAST(PINCODE AS STRING) AS PINCODE,
        TRY_CAST(COORDINATES AS STRING) AS COORDINATES,
        TRY_CAST(PRIMARYFLAG AS STRING) AS PRIMARY_FLAG,
        TRY_CAST(ADDRESSTYPE AS STRING) AS ADDRESS_TYPE,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE, 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS CREATED_DT,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE, 'YYYY-MM-DD"T"HH24:MI:SS.FF6') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.CUSTOMERADDRESS_STM
) AS SOURCE ON TARGET.ADDRESS_ID = SOURCE.ADDRESS_ID
WHEN MATCHED
AND (
    TARGET.CUSTOMER_ID_FK != SOURCE.CUSTOMER_ID_FK
    OR TARGET.FLAT_NO != SOURCE.FLAT_NO
    OR TARGET.HOUSE_NO != SOURCE.HOUSE_NO
    OR TARGET.FLOOR != SOURCE.FLOOR
    OR TARGET.BUILDING != SOURCE.BUILDING
    OR TARGET.LANDMARK != SOURCE.LANDMARK
    OR TARGET.LOCALITY != SOURCE.LOCALITY
    OR TARGET.CITY != SOURCE.CITY
    OR TARGET.STATE != SOURCE.STATE
    OR TARGET.PINCODE != SOURCE.PINCODE
    OR TARGET.COORDINATES != SOURCE.COORDINATES
    OR TARGET.PRIMARY_FLAG != SOURCE.PRIMARY_FLAG
    OR TARGET.ADDRESS_TYPE != SOURCE.ADDRESS_TYPE
) THEN
UPDATE
SET TARGET.CUSTOMER_ID_FK = SOURCE.CUSTOMER_ID_FK,
    TARGET.FLAT_NO = SOURCE.FLAT_NO,
    TARGET.HOUSE_NO = SOURCE.HOUSE_NO,
    TARGET.FLOOR = SOURCE.FLOOR,
    TARGET.BUILDING = SOURCE.BUILDING,
    TARGET.LANDMARK = SOURCE.LANDMARK,
    TARGET.LOCALITY = SOURCE.LOCALITY,
    TARGET.CITY = SOURCE.CITY,
    TARGET.STATE = SOURCE.STATE,
    TARGET.PINCODE = SOURCE.PINCODE,
    TARGET.COORDINATES = SOURCE.COORDINATES,
    TARGET.PRIMARY_FLAG = SOURCE.PRIMARY_FLAG,
    TARGET.ADDRESS_TYPE = SOURCE.ADDRESS_TYPE,
    TARGET.CREATED_DT = SOURCE.CREATED_DT,
    TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        ADDRESS_ID,
        CUSTOMER_ID_FK,
        FLAT_NO,
        HOUSE_NO,
        FLOOR,
        BUILDING,
        LANDMARK,
        LOCALITY,
        CITY,
        STATE,
        PINCODE,
        COORDINATES,
        PRIMARY_FLAG,
        ADDRESS_TYPE,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.ADDRESS_ID,
        SOURCE.CUSTOMER_ID_FK,
        SOURCE.FLAT_NO,
        SOURCE.HOUSE_NO,
        SOURCE.FLOOR,
        SOURCE.BUILDING,
        SOURCE.LANDMARK,
        SOURCE.LOCALITY,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.PINCODE,
        SOURCE.COORDINATES,
        SOURCE.PRIMARY_FLAG,
        SOURCE.ADDRESS_TYPE,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );