USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE SCHEMA STAGE_SCH;
USE WAREHOUSE COMPUTE_WH;

--- STREAM OBJECT TO CAPTURE THE CHANGES IN LOCATION TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.LOCATION_STM ON TABLE STAGE_SCH.LOCATION APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON LOCATION TABLE THAT GETS DELTA DATA';
--- STREAM OBJECT TO CAPTURE THE CHANGES IN RESTAURANT TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.RESTAURANT_STM ON TABLE STAGE_SCH.RESTAURANT APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON RESTAURANT TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN CUSTOMER TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.CUSTOMER_STM ON TABLE STAGE_SCH.CUSTOMER APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON CUSTOMER TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN CUSTOMER TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.CUSTOMERADDRESS_STM ON TABLE STAGE_SCH.CUSTOMERADDRESS APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON CUSTOMERADDRESS TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN MENU TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.MENU_STM ON TABLE STAGE_SCH.MENU APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON MENU TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN MENU TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.DELIVERYAGENT_STM ON TABLE STAGE_SCH.DELIVERYAGENT APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON DELIVERYAGENT TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN DELIVERY TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.DELIVERY_STM ON TABLE STAGE_SCH.DELIVERY APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON DELIVERY TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN ORDERS TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.ORDERS_STM ON TABLE STAGE_SCH.ORDERS APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON ORDERS TABLE THAT ONLY GETS DELTA DATA';
-- STREAM OBJECT TO CAPTURE THE CHANGES IN ORDERS TABLE. 
CREATE OR REPLACE STREAM STAGE_SCH.ORDERITEM_STM ON TABLE STAGE_SCH.ORDERITEM APPEND_ONLY = TRUE COMMENT = 'THIS IS THE APPEND-ONLY STREAM OBJECT ON ORDERITEM TABLE THAT ONLY GETS DELTA DATA';