USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
use schema common;
CREATE OR REPLACE TAG COMMON.PII_POLICY_TAG ALLOWED_VALUES 'PII',
    'PRICE',
    'SENSITIVE',
    'EMAIL' COMMENT = 'THIS IS PII POLICY TAG OBJECT';

CREATE OR REPLACE MASKING POLICY COMMON.PII_MASKING_POLICY AS (PII_TEXT STRING) RETURNS STRING->
    CASE
        WHEN CURRENT_ROLE() IN ('SYSADMIN', 'ACCOUNTADMIN') THEN PII_TEXT
        WHEN CURRENT_ROLE() IN ('USERADMIN') THEN
            CASE
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'PII' THEN REGEXP_REPLACE(PII_TEXT, SUBSTRING(PII_TEXT, 1, 7), 'XXX-XX-')
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'EMAIL' THEN REGEXP_REPLACE(PII_TEXT, SUBSTRING(PII_TEXT, 1, 7), 'XXX-XX-')
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'SENSITIVE' THEN REGEXP_REPLACE(PII_TEXT, SUBSTRING(PII_TEXT, 1, 7), 'XXX-XX-')
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'PHONE' THEN REGEXP_REPLACE(PII_TEXT, SUBSTRING(PII_TEXT, 1, 7), 'XXX-XX-')
            ELSE PII_TEXT
            END
        ELSE
            CASE
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'PII' THEN TO_VARCHAR('** PII **')
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'EMAIL' THEN TO_VARCHAR('** EMAIL **')
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'SENSITIVE' THEN TO_VARCHAR('** SENSITIVE **')
            WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('PII_POLICY_TAG') = 'PHONE' THEN TO_VARCHAR('** PHONE **')
            ELSE PII_TEXT
            END
    END;

ALTER TAG COMMON.PII_POLICY_TAG SET MASKING POLICY COMMON.PII_MASKING_POLICY;

