USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE SCHEMA CONSUMPTION_SCH;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE TABLE CONSUMPTION_SCH.RESTAURANT_DIM (
        RESTAURANT_HK NUMBER PRIMARY KEY,
        -- HASH KEY FOR THE RESTAURANT LOCATION
        RESTAURANT_ID NUMBER,
        -- RESTAURANT ID WITHOUT AUTO-INCREMENT
        NAME STRING(100),
        -- RESTAURANT NAME
        CUISINE_TYPE STRING,
        -- TYPE OF CUISINE OFFERED
        PRICING_FOR_TWO NUMBER(10, 2),
        -- PRICING FOR TWO PEOPLE
        RESTAURANT_PHONE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
        -- RESTAURANT PHONE NUMBER
        OPERATING_HOURS STRING(100),
        -- RESTAURANT OPERATING HOURS
        LOCATION_ID_FK NUMBER,
        -- FOREIGN KEY REFERENCE TO LOCATION
        ACTIVE_FLAG STRING(10),
        -- INDICATES IF THE RESTAURANT IS ACTIVE
        OPEN_STATUS STRING(10),
        -- INDICATES IF THE RESTAURANT IS CURRENTLY OPEN
        LOCALITY STRING(100),
        -- LOCALITY OF THE RESTAURANT
        RESTAURANT_ADDRESS STRING,
        -- FULL ADDRESS OF THE RESTAURANT
        LATITUDE NUMBER(9, 6),
        -- LATITUDE FOR THE RESTAURANT'S LOCATION
        LONGITUDE NUMBER(9, 6),
        -- LONGITUDE FOR THE RESTAURANT'S LOCATION
        EFF_START_DATE TIMESTAMP_TZ,
        -- EFFECTIVE START DATE FOR THE RECORD
        EFF_END_DATE TIMESTAMP_TZ,
        -- EFFECTIVE END DATE FOR THE RECORD (NULL IF ACTIVE)
        IS_CURRENT BOOLEAN -- INDICATES WHETHER THE RECORD IS THE CURRENT VERSION
    );
CREATE OR REPLACE TABLE CONSUMPTION_SCH.CUSTOMER_DIM (
        CUSTOMER_HK NUMBER PRIMARY KEY,
        -- SURROGATE KEY FOR THE CUSTOMER
        CUSTOMER_ID STRING NOT NULL,
        -- NATURAL KEY FOR THE CUSTOMER
        NAME STRING(100) NOT NULL,
        -- CUSTOMER NAME
        MOBILE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
        -- MOBILE NUMBER
        EMAIL STRING(100) WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),
        -- EMAIL
        LOGIN_BY_USING STRING(50),
        -- METHOD OF LOGIN
        GENDER STRING(10) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
        -- GENDER
        DOB DATE WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
        -- DATE OF BIRTH
        ANNIVERSARY DATE,
        -- ANNIVERSARY
        PREFERENCES STRING,
        -- PREFERENCES
        EFF_START_DATE TIMESTAMP_TZ,
        -- EFFECTIVE START DATE
        EFF_END_DATE TIMESTAMP_TZ,
        -- EFFECTIVE END DATE (NULL IF ACTIVE)
        IS_CURRENT BOOLEAN -- FLAG TO INDICATE THE CURRENT RECORD
    );
CREATE OR REPLACE TABLE CONSUMPTION_SCH.CUSTOMER_ADDRESS_DIM (
        CUSTOMER_ADDRESS_HK NUMBER PRIMARY KEY COMMENT 'CUSTOMER ADDRESS HK (EDW)',
        -- SURROGATE KEY (HASH KEY)
        ADDRESS_ID INT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- ORIGINAL PRIMARY KEY
        CUSTOMER_ID_FK STRING COMMENT 'CUSTOMER FK (SOURCE SYSTEM)',
        -- SURROGATE KEY FROM CUSTOMER DIMENSION (FOREIGN KEY)
        FLAT_NO STRING,
        -- FLAT NUMBER
        HOUSE_NO STRING,
        -- HOUSE NUMBER
        FLOOR STRING,
        -- FLOOR
        BUILDING STRING,
        -- BUILDING NAME
        LANDMARK STRING,
        -- LANDMARK
        LOCALITY STRING,
        -- LOCALITY
        CITY STRING,
        -- CITY
        STATE STRING,
        -- STATE
        PINCODE STRING,
        -- PINCODE
        COORDINATES STRING,
        -- GEO-COORDINATES
        PRIMARY_FLAG STRING,
        -- WHETHER IT'S THE PRIMARY ADDRESS
        ADDRESS_TYPE STRING,
        -- TYPE OF ADDRESS (E.G., HOME, OFFICE)
        -- SCD2 COLUMNS
        EFF_START_DATE TIMESTAMP_TZ,
        -- EFFECTIVE START DATE
        EFF_END_DATE TIMESTAMP_TZ,
        -- EFFECTIVE END DATE (NULL IF ACTIVE)
        IS_CURRENT BOOLEAN -- FLAG TO INDICATE THE CURRENT RECORD
    );
CREATE OR REPLACE TABLE CONSUMPTION_SCH.MENU_DIM (
        MENU_DIM_HK NUMBER PRIMARY KEY COMMENT 'MENU DIM HK (EDW)',
        -- HASH KEY GENERATED FOR MENU DIM TABLE
        MENU_ID INT NOT NULL COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- UNIQUE AND NON-NULL MENU_ID
        RESTAURANT_ID_FK INT NOT NULL COMMENT 'RESTAURANT FK (SOURCE SYSTEM)',
        -- IDENTIFIER FOR THE RESTAURANT
        ITEM_NAME STRING,
        -- NAME OF THE MENU ITEM
        DESCRIPTION STRING,
        -- DESCRIPTION OF THE MENU ITEM
        PRICE DECIMAL(10, 2),
        -- PRICE AS A NUMERIC VALUE WITH 2 DECIMAL PLACES
        CATEGORY STRING,
        -- FOOD CATEGORY (E.G., NORTH INDIAN)
        AVAILABILITY BOOLEAN,
        -- AVAILABILITY STATUS (TRUE/FALSE)
        ITEM_TYPE STRING,
        -- DIETARY CLASSIFICATION (E.G., VEGAN)
        EFF_START_DATE TIMESTAMP_NTZ,
        -- EFFECTIVE START DATE OF THE RECORD
        EFF_END_DATE TIMESTAMP_NTZ,
        -- EFFECTIVE END DATE OF THE RECORD
        IS_CURRENT BOOLEAN -- FLAG TO INDICATE IF THE RECORD IS CURRENT (TRUE/FALSE)
    );
CREATE OR REPLACE TABLE CONSUMPTION_SCH.DELIVERY_AGENT_DIM (
        DELIVERY_AGENT_HK NUMBER PRIMARY KEY COMMENT 'DELIVERY AGEND DIM HK (EDW)',
        -- HASH KEY FOR UNIQUE IDENTIFICATION
        DELIVERY_AGENT_ID NUMBER NOT NULL COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
        -- BUSINESS KEY
        NAME STRING NOT NULL,
        -- DELIVERY AGENT NAME
        PHONE STRING UNIQUE,
        -- PHONE NUMBER, UNIQUE
        VEHICLE_TYPE STRING,
        -- TYPE OF VEHICLE
        LOCATION_ID_FK NUMBER NOT NULL COMMENT 'LOCATION FK (SOURCE SYSTEM)',
        -- LOCATION ID
        STATUS STRING,
        -- CURRENT STATUS OF THE DELIVERY AGENT
        GENDER STRING,
        -- GENDER
        RATING NUMBER(4, 2),
        -- RATING WITH ONE DECIMAL PRECISION
        EFF_START_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        -- EFFECTIVE START DATE
        EFF_END_DATE TIMESTAMP,
        -- EFFECTIVE END DATE (NULL FOR ACTIVE RECORD)
        IS_CURRENT BOOLEAN DEFAULT TRUE
    );
CREATE OR REPLACE TABLE CONSUMPTION_SCH.DATE_DIM (
        DATE_DIM_HK NUMBER PRIMARY KEY COMMENT 'MENU DIM HK (EDW)',
        -- SURROGATE KEY FOR DATE DIMENSION
        CALENDAR_DATE DATE UNIQUE,
        -- THE ACTUAL CALENDAR DATE
        YEAR NUMBER,
        -- YEAR
        QUARTER NUMBER,
        -- QUARTER (1-4)
        MONTH NUMBER,
        -- MONTH (1-12)
        WEEK NUMBER,
        -- WEEK OF THE YEAR
        DAY_OF_YEAR NUMBER,
        -- DAY OF THE YEAR (1-365/366)
        DAY_OF_WEEK NUMBER,
        -- DAY OF THE WEEK (1-7)
        DAY_OF_THE_MONTH NUMBER,
        -- DAY OF THE MONTH (1-31)
        DAY_NAME STRING -- NAME OF THE DAY (E.G., MONDAY)
    ) COMMENT = 'DATE DIMENSION TABLE CREATED USING MIN OF ORDER DATA.';
CREATE OR REPLACE TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT (
        ORDER_ITEM_FACT_SK NUMBER AUTOINCREMENT COMMENT 'SURROGATE KEY (EDW)',
        -- SURROGATE KEY FOR THE FACT TABLE
        ORDER_ITEM_ID NUMBER COMMENT 'ORDER ITEM FK (SOURCE SYSTEM)',
        -- NATURAL KEY FROM THE SOURCE DATA
        ORDER_ID NUMBER COMMENT 'ORDER FK (SOURCE SYSTEM)',
        -- REFERENCE TO THE ORDER DIMENSION
        CUSTOMER_DIM_KEY NUMBER COMMENT 'ORDER FK (SOURCE SYSTEM)',
        -- REFERENCE TO THE CUSTOMER DIMENSION
        CUSTOMER_ADDRESS_DIM_KEY NUMBER,
        -- REFERENCE TO THE CUSTOMER DIMENSION
        RESTAURANT_DIM_KEY NUMBER,
        -- REFERENCE TO THE RESTAURANT DIMENSION
        RESTAURANT_LOCATION_DIM_KEY NUMBER,
        -- REFERENCE TO THE RESTAURANT DIMENSION
        MENU_DIM_KEY NUMBER,
        -- REFERENCE TO THE MENU DIMENSION
        DELIVERY_AGENT_DIM_KEY NUMBER,
        -- REFERENCE TO THE DELIVERY AGENT DIMENSION
        ORDER_DATE_DIM_KEY NUMBER,
        -- REFERENCE TO THE DATE DIMENSION
        QUANTITY NUMBER,
        -- MEASURE
        PRICE NUMBER(10, 2),
        -- MEASURE
        SUBTOTAL NUMBER(10, 2),
        -- MEASURE
        DELIVERY_STATUS VARCHAR,
        -- DELIVERY INFORMATION
        ESTIMATED_TIME VARCHAR -- DELIVERY INFORMATION
    );