USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA CONSUMPTION_SCH;
MERGE INTO CONSUMPTION_SCH.ORDER_ITEM_FACT AS TARGET USING(
    SELECT OI.ORDER_ITEM_ID AS ORDER_ITEM_ID,
        OI.ORDER_ID_FK AS ORDER_ID,
        C.CUSTOMER_HK AS CUSTOMER_DIM_KEY,
        CA.CUSTOMER_ADDRESS_HK AS CUSTOMER_ADDRESS_DIM_KEY,
        R.RESTAURANT_HK AS RESTAURANT_DIM_KEY,
        RL.RESTAURANT_LOCATION_HK AS RESTAURANT_LOCATION_DIM_KEY,
        M.MENU_DIM_HK AS MENU_DIM_KEY,
        DA.DELIVERY_AGENT_HK AS DELIVERY_AGENT_DIM_KEY,
        DD.DATE_DIM_HK AS ORDER_DATE_DIM_KEY,
        OI.QUANTITY::NUMBER(2) AS QUANTITY,
        OI.PRICE AS PRICE,
        OI.SUBTOTAL AS SUBTOTAL,
        O.PAYMENT_METHOD,
        D.DELIVERY_STATUS AS DELIVERY_STATUS,
        D.ESTIMATED_TIME AS ESTIMATED_TIME,
        FROM CLEAN_SCH.ORDERITEM_STM OI
        JOIN CLEAN_SCH.ORDERS_STM O ON OI.ORDER_ID_FK = O.ORDER_ID
        JOIN CLEAN_SCH.DELIVERY_STM D ON O.ORDER_ID = D.ORDER_ID_FK
        JOIN CONSUMPTION_SCH.CUSTOMER_DIM C ON O.CUSTOMER_ID_FK = C.CUSTOMER_ID
        JOIN CONSUMPTION_SCH.CUSTOMER_ADDRESS_DIM CA ON C.CUSTOMER_ID = CA.CUSTOMER_ID_FK
        JOIN CONSUMPTION_SCH.RESTAURANT_DIM R ON O.RESTAURANT_ID_FK = R.RESTAURANT_ID
        JOIN CONSUMPTION_SCH.MENU_DIM M ON OI.MENU_ID_FK = M.MENU_ID
        JOIN CONSUMPTION_SCH.DELIVERY_AGENT_DIM DA ON D.DELIVERY_AGENT_ID_FK = DA.DELIVERY_AGENT_ID
        JOIN CONSUMPTION_SCH.RESTAURANT_LOCATION_DIM RL ON R.LOCATION_ID_FK = RL.LOCATION_ID
        JOIN CONSUMPTION_SCH.DATE_DIM DD ON DD.CALENDAR_DATE = DATE(O.ORDER_DATE)
) AS SOURCE ON TARGET.ORDER_ITEM_ID = SOURCE.ORDER_ITEM_ID
AND TARGET.ORDER_ID = SOURCE.ORDER_ID
WHEN MATCHED THEN -- UPDATE EXISTING FACT RECORD
UPDATE
SET TARGET.CUSTOMER_DIM_KEY = SOURCE.CUSTOMER_DIM_KEY,
    TARGET.CUSTOMER_ADDRESS_DIM_KEY = SOURCE.CUSTOMER_ADDRESS_DIM_KEY,
    TARGET.RESTAURANT_DIM_KEY = SOURCE.RESTAURANT_DIM_KEY,
    TARGET.RESTAURANT_LOCATION_DIM_KEY = SOURCE.RESTAURANT_LOCATION_DIM_KEY,
    TARGET.MENU_DIM_KEY = SOURCE.MENU_DIM_KEY,
    TARGET.DELIVERY_AGENT_DIM_KEY = SOURCE.DELIVERY_AGENT_DIM_KEY,
    TARGET.ORDER_DATE_DIM_KEY = SOURCE.ORDER_DATE_DIM_KEY,
    TARGET.QUANTITY = SOURCE.QUANTITY,
    TARGET.PRICE = SOURCE.PRICE,
    TARGET.SUBTOTAL = SOURCE.SUBTOTAL,
    TARGET.DELIVERY_STATUS = SOURCE.DELIVERY_STATUS,
    TARGET.ESTIMATED_TIME = SOURCE.ESTIMATED_TIME
    WHEN NOT MATCHED THEN -- INSERT NEW FACT RECORD
INSERT (
        ORDER_ITEM_ID,
        ORDER_ID,
        CUSTOMER_DIM_KEY,
        CUSTOMER_ADDRESS_DIM_KEY,
        RESTAURANT_DIM_KEY,
        RESTAURANT_LOCATION_DIM_KEY,
        MENU_DIM_KEY,
        DELIVERY_AGENT_DIM_KEY,
        ORDER_DATE_DIM_KEY,
        QUANTITY,
        PRICE,
        SUBTOTAL,
        DELIVERY_STATUS,
        ESTIMATED_TIME
    )
VALUES (
        SOURCE.ORDER_ITEM_ID,
        SOURCE.ORDER_ID,
        SOURCE.CUSTOMER_DIM_KEY,
        SOURCE.CUSTOMER_ADDRESS_DIM_KEY,
        SOURCE.RESTAURANT_DIM_KEY,
        SOURCE.RESTAURANT_LOCATION_DIM_KEY,
        SOURCE.MENU_DIM_KEY,
        SOURCE.DELIVERY_AGENT_DIM_KEY,
        SOURCE.ORDER_DATE_DIM_KEY,
        SOURCE.QUANTITY,
        SOURCE.PRICE,
        SOURCE.SUBTOTAL,
        SOURCE.DELIVERY_STATUS,
        SOURCE.ESTIMATED_TIME
    );