USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.RESTAURANT_LOCATION AS TARGET USING (
    SELECT CAST(LOCATIONID AS NUMBER) AS LOCATION_ID,
        CAST(CITY AS STRING) AS CITY,
        CASE
            WHEN CAST(STATE AS STRING) = 'DELHI' THEN 'NEW DELHI'
            ELSE CAST(STATE AS STRING)
        END AS STATE,
        CASE
            WHEN STATE = 'DELHI' THEN 'DL'
            WHEN STATE = 'MAHARASHTRA' THEN 'MH'
            WHEN STATE = 'UTTAR PRADESH' THEN 'UP'
            WHEN STATE = 'GUJARAT' THEN 'GJ'
            WHEN STATE = 'RAJASTHAN' THEN 'RJ'
            WHEN STATE = 'KERALA' THEN 'KL'
            WHEN STATE = 'PUNJAB' THEN 'PB'
            WHEN STATE = 'KARNATAKA' THEN 'KA'
            WHEN STATE = 'MADHYA PRADESH' THEN 'MP'
            WHEN STATE = 'ODISHA' THEN 'OR'
            WHEN STATE = 'CHANDIGARH' THEN 'CH'
            WHEN STATE = 'WEST BENGAL' THEN 'WB'
            WHEN STATE = 'SIKKIM' THEN 'SK'
            WHEN STATE = 'ANDHRA PRADESH' THEN 'AP'
            WHEN STATE = 'ASSAM' THEN 'AS'
            WHEN STATE = 'JAMMU AND KASHMIR' THEN 'JK'
            WHEN STATE = 'PUDUCHERRY' THEN 'PY'
            WHEN STATE = 'UTTARAKHAND' THEN 'UK'
            WHEN STATE = 'HIMACHAL PRADESH' THEN 'HP'
            WHEN STATE = 'TAMIL NADU' THEN 'TN'
            WHEN STATE = 'GOA' THEN 'GA'
            WHEN STATE = 'TELANGANA' THEN 'TG'
            WHEN STATE = 'CHHATTISGARH' THEN 'CG'
            WHEN STATE = 'JHARKHAND' THEN 'JH'
            WHEN STATE = 'BIHAR' THEN 'BR'
            ELSE NULL
        END AS STATE_CODE,
        CASE
            WHEN STATE IN (
                'DELHI',
                'CHANDIGARH',
                'PUDUCHERRY',
                'JAMMU AND KASHMIR'
            ) THEN 'Y'
            ELSE 'N'
        END AS IS_UNION_TERRITORY,
        CASE
            WHEN (
                STATE = 'DELHI'
                AND CITY = 'NEW DELHI'
            ) THEN TRUE
            WHEN (
                STATE = 'MAHARASHTRA'
                AND CITY = 'MUMBAI'
            ) THEN TRUE -- OTHER CONDITIONS FOR CAPITAL CITIES
            ELSE FALSE
        END AS CAPITAL_CITY_FLAG,
        CASE
            WHEN CITY IN (
                'MUMBAI',
                'DELHI',
                'BENGALURU',
                'HYDERABAD',
                'CHENNAI',
                'KOLKATA',
                'PUNE',
                'AHMEDABAD'
            ) THEN 'TIER-1'
            WHEN CITY IN (
                'JAIPUR',
                'LUCKNOW',
                'KANPUR',
                'NAGPUR',
                'INDORE',
                'BHOPAL',
                'PATNA',
                'VADODARA',
                'COIMBATORE',
                'LUDHIANA',
                'AGRA',
                'NASHIK',
                'RANCHI',
                'MEERUT',
                'RAIPUR',
                'GUWAHATI',
                'CHANDIGARH'
            ) THEN 'TIER-2'
            ELSE 'TIER-3'
        END AS CITY_TIER,
        CAST(ZIPCODE AS STRING) AS ZIP_CODE,
        CAST(ACTIVEFLAG AS STRING) AS ACTIVE_FLAG,
        TO_TIMESTAMP_TZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_TS,
        TO_TIMESTAMP_TZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS') AS MODIFIED_TS,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.LOCATION_STM
) AS SOURCE ON TARGET.LOCATION_ID = SOURCE.LOCATION_ID
WHEN MATCHED
AND (
    TARGET.CITY != SOURCE.CITY
    OR TARGET.STATE != SOURCE.STATE
    OR TARGET.STATE_CODE != SOURCE.STATE_CODE
    OR TARGET.IS_UNION_TERRITORY != SOURCE.IS_UNION_TERRITORY
    OR TARGET.CAPITAL_CITY_FLAG != SOURCE.CAPITAL_CITY_FLAG
    OR TARGET.CITY_TIER != SOURCE.CITY_TIER
    OR TARGET.ZIP_CODE != SOURCE.ZIP_CODE
    OR TARGET.ACTIVE_FLAG != SOURCE.ACTIVE_FLAG
    OR TARGET.MODIFIED_TS != SOURCE.MODIFIED_TS
) THEN
UPDATE
SET TARGET.CITY = SOURCE.CITY,
    TARGET.STATE = SOURCE.STATE,
    TARGET.STATE_CODE = SOURCE.STATE_CODE,
    TARGET.IS_UNION_TERRITORY = SOURCE.IS_UNION_TERRITORY,
    TARGET.CAPITAL_CITY_FLAG = SOURCE.CAPITAL_CITY_FLAG,
    TARGET.CITY_TIER = SOURCE.CITY_TIER,
    TARGET.ZIP_CODE = SOURCE.ZIP_CODE,
    TARGET.ACTIVE_FLAG = SOURCE.ACTIVE_FLAG,
    TARGET.MODIFIED_TS = SOURCE.MODIFIED_TS,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        LOCATION_ID,
        CITY,
        STATE,
        STATE_CODE,
        IS_UNION_TERRITORY,
        CAPITAL_CITY_FLAG,
        CITY_TIER,
        ZIP_CODE,
        ACTIVE_FLAG,
        CREATED_TS,
        MODIFIED_TS,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.LOCATION_ID,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.STATE_CODE,
        SOURCE.IS_UNION_TERRITORY,
        SOURCE.CAPITAL_CITY_FLAG,
        SOURCE.CITY_TIER,
        SOURCE.ZIP_CODE,
        SOURCE.ACTIVE_FLAG,
        SOURCE.CREATED_TS,
        SOURCE.MODIFIED_TS,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );