USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
MERGE INTO CLEAN_SCH.ORDER_ITEM AS TARGET USING (
    SELECT TRY_CAST(ORDERID AS NUMBER) AS ORDER_ITEM_ID,
        TRY_CAST(ORDERID AS NUMBER) AS ORDER_ID_FK,
        TRY_CAST(MENUID AS NUMBER) AS MENU_ID_FK,
        TRY_CAST(QUANTITY AS NUMBER(38, 3)) AS QUANTITY,
        TRY_CAST(PRICE AS NUMBER(38, 3)) AS PRICE,
        TRY_CAST(SUBTOTAL AS NUMBER(38, 3)) AS SUBTOTAL,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF6') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM STAGE_SCH.ORDERITEM_STM
) AS SOURCE ON TARGET.ORDER_ITEM_ID = SOURCE.ORDER_ITEM_ID
WHEN MATCHED
AND (
    TARGET.ORDER_ID_FK != SOURCE.ORDER_ID_FK
    OR TARGET.MENU_ID_FK != SOURCE.MENU_ID_FK
    OR TARGET.QUANTITY != SOURCE.QUANTITY
    OR TARGET.PRICE != SOURCE.PRICE
    OR TARGET.SUBTOTAL != SOURCE.SUBTOTAL
) THEN
UPDATE
SET TARGET.ORDER_ID_FK = SOURCE.ORDER_ID_FK,
    TARGET.MENU_ID_FK = SOURCE.MENU_ID_FK,
    TARGET.QUANTITY = SOURCE.QUANTITY,
    TARGET.PRICE = SOURCE.PRICE,
    TARGET.SUBTOTAL = SOURCE.SUBTOTAL,
    --UPDATING AUDIT COLUMS--
    TARGET.CREATED_DT = SOURCE.CREATED_DT,
    TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
    TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
    TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
    TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
    TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
    WHEN NOT MATCHED THEN
INSERT (
        ORDER_ITEM_ID,
        ORDER_ID_FK,
        MENU_ID_FK,
        QUANTITY,
        PRICE,
        SUBTOTAL,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
VALUES (
        SOURCE.ORDER_ITEM_ID,
        SOURCE.ORDER_ID_FK,
        SOURCE.MENU_ID_FK,
        SOURCE.QUANTITY,
        SOURCE.PRICE,
        SOURCE.SUBTOTAL,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );